# Generated by Django 4.2.5 on 2023-10-05 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=120, unique=True)),
                ('location', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=300)),
                ('date', models.DateField()),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='artist.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('caption', models.CharField(max_length=120)),
                ('enclosure', models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal'), ('square', 'Square')], max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events.event')),
            ],
        ),
    ]
