# Generated by Django 4.2.5 on 2023-09-28 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('venue', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('caption', models.CharField(max_length=120)),
                ('enclosure', models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal'), ('cuadrado', 'Cuadrado')], max_length=20)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.gallery')),
            ],
        ),
    ]
