# Generated by Django 4.2.5 on 2023-10-05 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='photos/')),
                ('caption', models.CharField(max_length=120)),
                ('enclosure', models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal'), ('square', 'Square')], max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='events.event')),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
