# Generated by Django 4.2.5 on 2023-09-29 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
    ]
