# Generated by Django 4.2.5 on 2023-09-29 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_gallery_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='gallery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='events.gallery'),
        ),
    ]
